# NumPy Indexing, Selection and operation
how to select elements or groups of elements from an array.

In [2]:
import numpy as np

In [6]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
array[5]

5

In [9]:
array[5:8]

array([5, 6, 7])

In [13]:
array[:1]

array([0])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend using the comma notation for clarity.

In [15]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
array_2d[0]

array([1, 2, 3])

# NumPy Operations

In [19]:
x = np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x + x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
x * x 

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [25]:
x - x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Universal Array Functions

In [26]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [27]:
# exponential
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [28]:
# logarithm
np.log(x) 

C:\Users\junai\AppData\Local\Temp\ipykernel_11776\3433472475.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [29]:
# sin
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

## Summary Statistics on Arrays

In [31]:
x.sum()

45

In [33]:
x.mean()

4.5

In [35]:
x.min()

0

In [37]:
x.max()

9

In [39]:
x.std()

2.8722813232690143

In [40]:
x.var()

8.25